### DISCUSSION TITLE
Data 100 at UC Berkeley

### DISCUSSION THREAD

**Discussion by surajrampure** [kevinlin1/just-the-class#12] [Show and tell]
Data 100 at UC Berkeley has used some variation of Just the Class since Fall 2019; here's a link to the latest iteration: https://ds100.org/fa21/

**Comment by ykharitonova** [comment]
@surajrampure How did you add the "LINKS" heading on the sidebar?

**Reply by surajrampure** [reply]
To be honest, I don't remember specifically, as [that's not how I do it now](https://dsc10.com). But here's the source for that website: https://github.com/DS-100/fa21/blob/gh-pages/_config.yml

**Reply by ykharitonova** [reply]
Thank you very much!

@kevinlin1 I'm not seeing what in the config that would make the "LInks" header appear on the sidebar. If you know off the top of your head how to add headers/categories to the sidebar, I'd love some guidance. Otherwise, I'll plan to look into it over the weekend and figure out where the magic sauce is hiding.

**Reply by kevinlin1** [reply]
Hi @ykharitonova, great to see you around again and thanks for contributing the patch a while back. I removed the `nav_links` configuration feature in [v0.3.2-0](https://github.com/kevinlin1/just-the-class/releases/tag/v0.3.2-0) because [Just the Docs added support for Jekyll Collections](https://pmarsceill.github.io/just-the-docs/docs/configuration/#document-collections). My [CSE 143 Autumn 2020 course website](https://courses.cs.washington.edu/courses/cse143/20au/) uses this feature.

It does make adding links to external websites in the navigation sidebar harder to do. I think this is a good thing though since the sidebar is intended for links to internal pages on the website. I recommend putting external links in the [Auxiliary links](https://pmarsceill.github.io/just-the-docs/docs/configuration/#aux-links), which will add your external links as buttons to the right of the search bar. External nav links can be a consistency problem—it's unexpected because the other nav links point to internal pages.

If you'd really like the `nav_links` feature, you can check out [how I integrated it](https://gitlab.cs.washington.edu/cse332-20wi/website/-/blob/master/_layouts/default.html#L23-34) in my CSE 332 Winter 2020 course website's `_layouts/default.html` file. You can then add `nav_links` to your `_config.yml` as follows.

```
nav_links:
  Campuswire:
    - 'https://campuswire.com/c/G06A1EF46'
  Feedback:
    - 'https://feedback.cs.washington.edu/'
  GitLab:
    - 'https://gitlab.cs.washington.edu/cse332-20wi-students'
  Gradescope:
    - 'https://www.gradescope.com/courses/72067'
  Panopto:
    - 'https://canvas.uw.edu/courses/1352390/external_tools/21130'
```
