### ISSUE TITLE
Unable to display more than one section on the same day

### ISSUE THREAD

**Issue by ykharitonova** [kevinlin1/just-the-class#4]
Hello!

I'm working on the `_schedules/weekly.md` file and I noticed that I am unable to display more than one section on the same day. Here's what I have for one of the days:
```
...
  Wednesday:
    Section:
      start: 10:00 AM
      end: 10:50 AM
      location: Zoom
    Section:
      start: 11:00 AM
      end: 11:50 AM
      location: Zoom
...
```
The resulting page displays only the 11AM section. Am I able to fix this issue on my end?

Also, where can I change the color of each type of event?

Thank you in advance for looking into this!
